Imported Upstream version 2.42

diff --git a/fslint/finded b/fslint/finded
--- a/fslint/finded
+++ b/fslint/finded
@@ -14,13 +14,13 @@
 # See the GNU General Public License for more details,
 # which is available at www.gnu.org
 
-script_dir=`dirname "$0"`              #directory of this script
-script_dir=`readlink -f "$script_dir"` #Make sure absolute path
+script_dir=$(dirname "$0")              #directory of this script
+script_dir=$(readlink -f "$script_dir") #Make sure absolute path
 
 . "$script_dir"/supprt/fslver
 
 Usage() {
-	ProgName=`basename "$0"`
+	ProgName=$(basename "$0")
 	echo "find Empty Directory branches.
 Usage: $ProgName [[-r] [-f] paths(s) ...]
 
@@ -43,6 +43,12 @@ done
 . "$script_dir"/supprt/getfpf -f "$argsToPassOn"
 #forcing -f as if specify an empty dir it would not display
 
+#flag trailing / as an error
+if printf "%s\n" "$@" | tr -s '/' | grep -q './$'; then
+    echo "Error: trailing '/' in a parameter is not allowed" >&2
+    exit 1
+fi
+
 (
 #get all dirs
 find "$@" -type d ! -name "*$LF*" -printf "$FPF\n" |
@@ -54,7 +60,7 @@ find "$@" ! -type d ! -name "*$LF*" -printf "%h\n" |
 uniq | #quick merge of dir names for each file
 sed -n ':s; p; s#/\{0,\}[^/]\{1,\}$##; /./b s' #separate dir nodes
 #Ensure we exclude parents to specified absolute dirs
-find "$@" -maxdepth 0 ! -name "*$LF*" -printf "%h\n" |
+find "$@" -maxdepth 0 ! -name "*$LF*" -printf "%h\n%h\n" |
 sed '/^\//!d' | #only process absolute dirs
 sed -n ':s; p; s#/\{0,\}[^/]\{1,\}$##; /./b s' #separate dir nodes
 ) |
